# This is a basic workflow to help you get started with Actions

name: CI

env: 
  DOCKERHUB_REPO: mcrank/twix

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.docker_meta.outputs.tags }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Github Tag Bump
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          WITH_V: 'true'
          DEFAULT_BUMP: patch

      - name: Generate Docker Tags
        if: startsWith(github.ref, 'refs/tags/v')
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=semver,pattern={{raw}},priority=30
            type=semver,pattern={{raw}},suffix=-{{date ''}},priority=25
            type=raw,value=${{ github.ref_name }},suffix=-{{date ''}},priority=24
            type=sha,priority=20
            type=sha,format=long,priority=15
  debug:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Output tags
        run: echo "${{ needs.build.outputs.tags[0] }}"
