name: Manual Deploy

on:
  workflow_dispatch:
  
jobs:
  debug:
    name: Inputs outputs
    runs-on: ubuntu-latest
    
    env:
      DEPLOYMENT_IMAGE: " mobilecoin/twix:${{ github.ref_name }}"
    
    steps:
      - name: Inputs
        run: echo ${DEPLOYMENT_IMAGE}
