name: Manual Deploy

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  ENV_CONTEXT: ${{ toJson(env) }}
  JOB_CONTEXT: ${{ toJson(job) }}
  STEPS_CONTEXT: ${{ toJson(steps) }}
  RUNNER_CONTEXT: ${{ toJson(runner) }}

on:
  push:
    tags:
      - "v*"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Github Context
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Env Context
        run: |
          echo "$ENV_CONTEXT"

      - name: Job Context
        run: |
          echo "$JOB_CONTEXT"

      - name: Steps Context
        run: |
          echo "$STEPS_CONTEXT"

      - name: Runner Context
        run: |
          echo "$RUNNER_CONTEXT"

  debug:
    name: Inputs outputs
    runs-on: ubuntu-latest
    # if: startsWith(github.event.ref, 'feature/')

    env:
      DEPLOYMENT_IMAGE: "mobilecoin/twix:${{ github.ref_name }}"

    steps:
      - name: Inputs
        run: echo ${DEPLOYMENT_IMAGE}

      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.19.0
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C01V90RS9NH" #web-app-bots
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n*Twix ${{ github.ref_name }} Deployment Successful*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Link:*\n[${{ github.repository }}](${{ github.event.head_commit.url }})\n*Run #:*\n${{ github.run_number }}\n*Commit:*\n ${{ github.sha }}"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://p7.hiclipart.com/preview/564/823/637/success-kid-desktop-wallpaper-internet-meme-infant-meme.jpg",
                    "alt_text": "success kid"
                  }
                }
              ]
            }

# https://i.imgflip.com/1g8tc5.jpg
# {
#   "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
#   "blocks": [
#     {
#       "type": "section",
#       "text": {
#         "type": "mrkdwn",
#         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
#       }
#     }
#   ]
# }
