name: Manual Deploy

# env:
#   MY_VAR: World!
#   MY_OTHER_VAR: "Hello/${{ MY_VAR }}"

on:
  workflow_dispatch:
  push:

jobs:
  debug:
    name: Inputs outputs
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/branch/feature/*')

    env:
      DEPLOYMENT_IMAGE: "mobilecoin/twix:${{ github.ref_name }}"

    steps:
      - name: Inputs
        run: echo ${DEPLOYMENT_IMAGE}

      - name: Post to Slack
        uses: slackapi/slack-github-action@v1.19.0
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C01V90RS9NH" #web-app-bots
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }

      - name: Env Echo
        run: echo ${MY_OTHER_VAR}
