name: Manual Deploy

env:
  DOCKERHUB_REPO: mobilecoin/twix

on:
  workflow_dispatch:
  
jobs:
  debug:
    name: Inputs outputs
    runs-on: ubuntu-latest
    
    env:
      DEPLOYMENT_IMAGE: ${{ env.DOCKERHUB_REPO }}:${{ github.ref_name }}
    
    steps:
      - name: Inputs
        run: echo ${DEPLOYMENT_IMAGE}
