name: Manual Deploy

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  push:
    tags:
      - "v*"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Github Context
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Failure
        run: exit 1

  debug:
    name: Inputs outputs
    runs-on: ubuntu-latest
    # if: startsWith(github.event.ref, 'feature/')

    env:
      DEPLOYMENT_IMAGE: "mobilecoin/twix:${{ github.ref_name }}"

    steps:
      - name: Inputs
        run: echo ${DEPLOYMENT_IMAGE}

      - name: Post to Slack Success
        if: success()
        uses: slackapi/slack-github-action@v1.19.0
        id: slack_success
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C01V90RS9NH" #web-app-bots
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: *${{ job.status }}*\n\n"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Version *${{ github.ref_name }}*\n\nStatus: *Successful*\n\nRun #: *${{ github.run_number }}*\n\nAuthor: *${{github.event.head_commit.author.username }}*"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://tinyurl.com/5es9sm27",
                    "alt_text": "computer thumbnail"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link to Workflow>*"
                  }
                }
              ]
            }

      - name: Post to Slack Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.19.0
        id: slack_failure
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C01V90RS9NH" #web-app-bots
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: *${{ job.status }}*\n\n"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Version *${{ github.ref_name }}*\n\nStatus: *Failed*\n\nRun #: *${{ github.run_number }}*\n\nAuthor: *${{github.event.head_commit.author.username }}*"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://tinyurl.com/mr2yuu4d",
                    "alt_text": "computer thumbnail"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Link to Workflow>*"
                  }
                }
              ]
            }
